application: tpm
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /admin.*
  script: blog/admin.py
  login: required

- url: /blog/help.*
  script: blog/help.py

- url: /forum/admin.*
  script: forum/admin.py
  login: required

- url: /forum.*
  script: forum/forum.py

- url: /help.*
  script: misc/help.py

- url: /code
  script: misc/code.py

- url: /.*
  script: blog/blog.py