application: homepage2303
version: 2
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /forum/admin/.*
  script: forum/admin.py
  login: required

- url: /forum/.*
  script: forum/forum.py

