application: tpm
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /admin.*
  script: blog/admin.py
  login: required

- url: /forum/admin.*
  script: forum/admin.py
  login: required

- url: /forum.*
  script: forum/forum.py

- url: /entry.*
  script: blog/blog.py

- url: /
  script: blog/blog.py

- url: /.*
  script: misc/misc.py